export const CREATE_BOOK_PDF_REQUEST = "CREATE_BOOK_PDF_REQUEST";
export const CREATE_BOOK_PDF_SUCCESS = "CREATE_BOOK_PDF_SUCCESS";
export const CREATE_BOOK_PDF_FAIL = "CREATE_BOOK_PDF_FAIL";

export const GET_ALL_BOOK_PDF_REQUEST = "GET_ALL_BOOK_PDF_REQUEST";
export const GET_ALL_BOOK_PDF_SUCCESS = "GET_ALL_BOOK_PDF_SUCCESS";
export const GET_ALL_BOOK_PDF_FAIL = "GET_ALL_BOOK_PDF_FAIL";

export const GET_SINGLE_BOOK_PDF_REQUEST = "GET_SINGLE_BOOK_PDF_REQUEST";
export const GET_SINGLE_BOOK_PDF_SUCCESS = "GET_SINGLE_BOOK_PDF_SUCCESS";
export const GET_SINGLE_BOOK_PDF_FAIL = "GET_SINGLE_BOOK_PDF_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
