export const DOWNLOAD_BOOK_PDF_REQUEST = "DOWNLOAD_BOOK_PDF_REQUEST";
export const DOWNLOAD_BOOK_PDF_SUCCESS = "DOWNLOAD_BOOK_PDF_SUCCESS";
export const DOWNLOAD_BOOK_PDF_FAIL = "DOWNLOAD_BOOK_PDF_FAIL";
